# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'channel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(134, 203)
        self.formLayout = QtWidgets.QFormLayout(Frame)
        self.formLayout.setObjectName("formLayout")
        self.checkBox = QtWidgets.QCheckBox(Frame)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.dial = QtWidgets.QDial(Frame)
        self.dial.setObjectName("dial")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.dial)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Frame)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.toolButton = QtWidgets.QToolButton(Frame)
        self.toolButton.setObjectName("toolButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.toolButton)
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label_5)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.checkBox.setText(_translate("Frame", "Enabled"))
        self.label.setText(_translate("Frame", "Set point"))
        self.toolButton.setText(_translate("Frame", "..."))
        self.label_2.setText(_translate("Frame", "Voltage"))
        self.label_3.setText(_translate("Frame", "100 V"))
        self.label_4.setText(_translate("Frame", "Current"))
        self.label_5.setText(_translate("Frame", "100 uA"))
